Updated phing/phing to 3.0
vufind-org/vufindharvest pull request #22
Opened 2024-06-18 19:30 UTC by sturkel89

I updated build.xml and composer.json to be compatible with phing/phing v3.0.

2024-06-18 20:03 UTC, demiankatz requested changes
Didn't have time for a full review but noticed one small thing...

2024-06-18 20:03 UTC, demiankatz commented on build.xml
> +    <exec executable="composer install">
I think "install" needs to be an arg line here.

2024-06-18 20:19 UTC, sturkel89 commented on build.xml
> +    <exec executable="composer install">
Good catch! I just made that change. :)

2024-06-19 20:18 UTC, demiankatz requested changes
@sturkel89, thanks for the fixes. I've noticed a couple of new things that need attention, though you couldn't possibly have known about them (and I only learned about the second earlier today). I think once these adjustments are made, we can make this live, and the other projects should generally be pretty easy to bring in sync with this one since they're all set up quite similarly.

2024-06-19 20:18 UTC, demiankatz commented on build.xml
> +   <target name="pdepend">
This whole pdepend block is no longer used and should be removed. (Not related to your changes -- but we might as well clean it up while we're updating things).

2024-06-19 20:18 UTC, demiankatz commented on build.xml
> +    <exec dir="${srcdir}" executable="${phpunit_command}" passthru="true" checkreturn="true">
Ere and I finished upgrading Phing to 3.0 in the main project today, and we discovered a problem: in some cases, the phpunit_command property gets set to an executable plus arguments, and that breaks the new system here. The workaround was to create a new "sh" property that specifies the Unix shell command, and then make _that_ the executable while putting everything else into the argument line.

Here's where the new property is set up at the top of the file:

https://github.com/vufind-org/vufind/blob/dev/build.xml#L3

And here is how things are put together in the phpunit commands:

https://github.com/vufind-org/vufind/blob/dev/build.xml#L369-L370

So, for example, these two lines would become:

```
<exec dir="${srcdir}" executable="${sh}" passthru="true" checkreturn="true">
  <arg line="-c &apos;${phpunit_command} -dzend.enable_gc=0 --log-junit ${builddir}/reports/phpunit.xml --coverage-clover ${builddir}/reports/coverage/clover.xml --coverage-html ${builddir}/reports/coverage/&apos;" />
```

(Note the `-c &apos;${phpunit_command} ... &apos;` wrapped around everything to make it a command to run with the shell).

2024-06-19 20:19 UTC, demiankatz commented on build.xml
> +   <target name="pdepend">
(The pdepend tool was discontinued last year... I removed it from composer.json and our Jenkins setup, but I must have forgotten to delete it from build.xml as well).

2024-07-08 11:24 UTC, demiankatz approved these changes
Thanks, @sturkel89!

2024-07-08 11:26 UTC, merged